Dockerization
Kool-Kids-Klan/king-of-the-castle pull request #59
Opened 2022-02-10 00:33 UTC by Puckoland

2022-02-10 00:34 UTC, Puckoland commented
resolves #3

2022-02-11 17:57 UTC, danieltimko commented on server/kotc_database/src/lib.rs
> +            let database_url = "postgres://postgres:password@db/kotc".to_string();
eliminate hardcoded credentials

2022-02-11 17:58 UTC, danieltimko requested changes

2022-02-11 17:58 UTC, danieltimko commented on server/kotc_database/src/lib.rs
> +            let database_url = "postgres://postgres:password@db/kotc".to_string();
eliminate hardcoded credentials

2022-02-11 21:40 UTC, revolko approved these changes

2022-02-13 21:46 UTC, danieltimko approved these changes

2022-02-13 21:48 UTC, danieltimko commented on server/kotc_database/src/lib.rs
> +                _ => "postgres://postgres:password@db/kotc".to_string(),
Perhaps it would be better to panic when env var is not set? Easier to debug what's going on

2022-02-15 19:48 UTC, merged

2022-02-17 01:23 UTC, Puckoland commented
resolved #68